// Login actions
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

//Employees actions
export const EMPLOYEES_FETCH_START = "EMPLOYEES_FETCH_START";
export const EMPLOYEES_FETCH_SUCCESS = "EMPLOYEES_FETCH_SUCCESS";
export const EMPLOYEES_FETCH_FAIL = "EMPLOYEES_FETCH_FAIL";
// Employee actions
export const EMPLOYEE_SELECT = "EMPLOYEE_SELECT";
export const EMPLOYEE_FETCH_START = "EMPLOYEE_FETCH_START";
export const EMPLOYEE_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";
export const EMPLOYEE_FETCH_FAIL = "EMPLOYEE_FETCH_FAIL";
export const EMPLOYEE_ADD_START = "EMPLOYEE_ADD_START";
export const EMPLOYEE_ADD_SUCCESS = "EMPLOYEE_ADD_SUCCESS";
export const EMPLOYEE_ADD_FAIL = "EMPLOYEE_ADD_FAIL";
export const EMPLOYEE_EDIT_START = "EMPLOYEE_EDIT_START";
export const EMPLOYEE_EDIT_SUCCESS = "EMPLOYEE_EDIT_SUCCESS";
export const EMPLOYEE_EDIT_FAIL = "EMPLOYEE_EDIT_FAIL";
export const EMPLOYEE_CANCEL = "EMPLOYEE_CANCEL";
export const EMPLOYEE_DELETE_START = "EMPLOYEE_DELETE_START";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL";

//Customers actions
export const CUSTOMERS_FETCH_START = "CUSTOMERS_FETCH_START";
export const CUSTOMERS_FETCH_SUCCESS = "CUSTOMERS_FETCH_SUCCESS";
export const CUSTOMERS_FETCH_FAIL = "CUSTOMERS_FETCH_FAIL";

export const CUSTOMER_SELECT = "CUSTOMER_SELECT";
export const CUSTOMER_FETCH_START = "CUSTOMER_FETCH_START";
export const CUSTOMER_FETCH_SUCCESS = "CUSTOMER_FETCH_SUCCESS";
export const CUSTOMER_FETCH_FAIL = "CUSTOMER_FETCH_FAIL";
export const CUSTOMER_ADD_START = "CUSTOMER_ADD_START";
export const CUSTOMER_ADD_SUCCESS = "CUSTOMER_ADD_SUCCESS";
export const CUSTOMER_ADD_FAIL = "CUSTOMER_ADD_FAIL";
export const CUSTOMER_EDIT_START = "CUSTOMER_EDIT_START";
export const CUSTOMER_EDIT_SUCCESS = "CUSTOMER_EDIT_SUCCESS";
export const CUSTOMER_EDIT_FAIL = "CUSTOMER_EDIT_FAIL";
export const CUSTOMER_CANCEL = "CUSTOMER_CANCEL";
export const CUSTOMER_DELETE_START = "CUSTOMER_DELETE_START";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL";

//Projects Actions
export const PROJECTS_FETCH_START = "PROJECTS_FETCH_START";
export const PROJECTS_FETCH_SUCCESS = "PROJECTS_FETCH_SUCCESS";
export const PROJECTS_FETCH_FAIL = "PROJECTS_FETCH_FAIL";

export const PROJECT_SELECT = "PROJECT_SELECT";
export const PROJECT_FETCH_START = "PROJECT_FETCH_START";
export const PROJECT_FETCH_SUCCESS = "PROJECT_FETCH_SUCCESS";
export const PROJECT_FETCH_FAIL = "PROJECT_FETCH_FAIL";
export const PROJECT_ADD_START = "PROJECT_ADD_START";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_ADD_FAIL = "PROJECT_ADD_FAIL";
export const PROJECT_EDIT_START = "PROJECT_EDIT_START";
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS";
export const PROJECT_EDIT_FAIL = "PROJECT_EDIT_FAIL";
export const PROJECT_CANCEL = "PROJECT_CANCEL";
export const PROJECT_DELETE_START = "PROJECT_DELETE_START";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";

