export const LOAD_EMPLOYEES = "LOAD_EMPLOYEES";
export const LOAD_EMPLOYEES_SUCCESS = "LOAD_EMPLOYEES_SUCCESS";
export const LOAD_EMPLOYEES_FAILURE = "LOAD_EMPLOYEES_FAILURE";

export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const LOAD_PROJECTS_FAILURE = "LOAD_PROJECTS_FAILURE";

export const LOAD_CUSTOMERS = "LOAD_CUSTOMERS";
export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCCESS";
export const LOAD_CUSTOMERS_FAILURE = "LOAD_CUSTOMERS_FAILURE";

export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";


export const FETCH_ANNUAL_REPORT = "FETCH_ANNUAL_REPORT";
export const FETCH_ANNUAL_REPORT_SUCCESS = "FETCH_ANNUAL_REPORT_SUCCESS";
export const FETCH_ANNUAL_REPORT_FAILURE = "FETCH_ANNUAL_REPORT_FAILURE";

export const FETCH_MONTHLY_REPORT = "FETCH_MONTHLY_REPORT";
export const FETCH_MONTHLY_REPORT_SUCCESS = "FETCH_MONTHLY_REPORT_SUCCESS";
export const FETCH_MONTHLY_REPORT_FAILURE = "FETCH_MONTHLY_REPORT_FAILURE";


export const FETCH_PROJECT_REPORT = "FETCH_PROJECT_REPORT";
export const FETCH_PROJECT_REPORT_SUCCESS = "FETCH_ANNUAL_PROJECT_SUCCESS";
export const FETCH_PROJECT_REPORT_FAILURE = "FETCH_ANNUAL_PROJECT_FAILURE";

export const LOAD_CALENDAR_MONTH = "LOAD_CALENDAR_MONTH";
export const LOAD_CALENDAR_MONTH_SUCCESS = "LOAD_CALENDAR_MONTH_SUCCESS";
export const LOAD_CALENDAR_MONTH_FAIL = "LOAD_CALENDAR_MONTH_FAIL";

export const TASK_EDITED_SUCCESS = "TASK_EDITED_SUCCESS";
export const TASK_EDITED_FAIL = "TASK_EDITED_FAIL";
export const TASK_ADD_SUCCESS = "TASK_EDITED_SUCCESS";
export const TASK_ADD_FAIL = "TASK_EDITED_FAIL";

export const ADD_DAY_SUCCESS = "ADD_DAY_SUCCESS";
export const ADD_DAY_FAIL = "ADD_DAY_FAIL";

export const ADD_DAY_WITH_TASK_SUCCESS = "ADD_DAY_WITH_TASK_SUCCESS";
export const ADD_DAY_WITH_TASK_FAIL = "ADD_DAY_WITH_TASK_FAIl";

export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";

export const RELOAD_CALENDAR = "RELOAD_CALENDAR";

export const FETCH_COMPANY_DASHBOARD = "FETCH_COMPANY_DASHBOARD";
export const FETCH_COMPANY_DASHBOARD_SUCCESS = "FETCH_COMPANY_DASHBOARD_SUCCESS";
export const FETCH_COMPANY_DASHBOARD_FAILURE = "FETCH_COMPANY_DASHBOARD_FAILURE";


export const FETCH_TEAM_DASHBOARD = "FETCH_TEAM_DASHBOARD";
export const FETCH_TEAM_DASHBOARD_SUCCESS = "FETCH_TEAM_DASHBOARD_SUCCESS";
export const FETCH_TEAM_DASHBOARD_FAILURE = "FETCH_TEAM_DASHBOARD_FAILURE";